=== Schlafendes24/translations/_.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Translation",
    "description": "Roles language translation schema",
    "type": "object",
    "properties": {
        "addToServer": {
            "type": "string",
            "msgType": "default"
        },
        "appDirectory": {
            "type": "string",
            "msgType": "default"
        },
        "supportServer": {
            "type": "string",
            "msgType": "default"
        },
        "website": {
            "type": "string",
            "msgType": "default"
        },
        "error": {
            "type": "string",
            "msgType": "error"
        },
        "command.help.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.title": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field1.name": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field1.value": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field2.name": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field2.value": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field3.name": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field3.value": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.footer": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.add.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.add.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.add.reply.error.everyone": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.error.managed": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.error.position": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.error.alreadyUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.autoroles.remove.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.remove.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.remove.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.autoroles.remove.reply.error.notUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.list.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.list.raw.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.list.reply.empty": {
            "type": "string",
            "msgType": "empty"
        },
        "command.autoroles.list.reply.warn.tooLong": {
            "type": "string",
            "msgType": "warn"
        },
        "command.stickyroles.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.add.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.add.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.add.reply.error.everyone": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.error.managed": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.error.position": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.error.alreadyUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.stickyroles.remove.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.remove.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.remove.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.stickyroles.remove.reply.error.notUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.list.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.list.raw.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.list.reply.empty": {
            "type": "string",
            "msgType": "empty"
        },
        "command.stickyroles.list.reply.warn.tooLong": {
            "type": "string",
            "msgType": "warn"
        },
        "command.connectroles.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.childRole.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.parentRole.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.reply.error.sameRoles": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.everyone": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.managed": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.position": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.childAlreadyConnected": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.parentAlreadyChild": {
            "type": "string",
            "msgType": "error",
            "deprecated": false
        },
        "command.connectroles.add.reply.error.childAlreadyParent": {
            "type": "string",
            "msgType": "error",
            "deprecated": false
        },
        "command.connectroles.add.reply.error.childAlreadyParentOfParent": {
            "type": "string",
            "msgType": "error",
            "deprecated": true
        },
        "command.connectroles.add.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.connectroles.remove.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.remove.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.remove.reply.success.childRemoved": {
            "type": "string",
            "msgType": "success"
        },
        "command.connectroles.remove.reply.success.parentRemoved": {
            "type": "string",
            "msgType": "success"
        },
        "command.connectroles.remove.reply.error.notConnected": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.list.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.list.raw.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.list.reply.empty": {
            "type": "string",
            "msgType": "empty"
        },
        "command.connectroles.list.reply.warn.tooLong": {
            "type": "string",
            "msgType": "warn"
        },
        "command.connectroles.sync.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.start": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.finish": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.progress": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.changes": {
            "type": "string",
            "msgType": "default"
        },
        "command.onCooldown": {
            "type": "string",
            "msgType": "default"
        },
        "command.error": {
            "type": "string",
            "msgType": "error"
        },
        "permission.required.all.text": {
            "type": "string",
            "msgType": "default"
        },
        "permission.required.missing.title": {
            "type": "string",
            "msgType": "warn"
        },
        "permission.required.missing.text": {
            "type": "string",
            "msgType": "default"
        },
        "permission.required.reauthorize": {
            "type": "string",
            "msgType": "default"
        }
    }
}

=== Schlafendes24/translations/fr.json
{
    "$schema": "./_.schema.json",
    "addToServer": "Ajouter au serveur",
    "appDirectory": "Répertoire des applications",
    "supportServer": "Serveur d'assistance",
    "website": "Site web",
    "error": "Erreur",
    "command.autoroles.description": "Attribue automatiquement des rôles aux nouveaux membres",
    "command.autoroles.add.description": "Ajouter un nouveau rôle Automatique",
    "command.autoroles.add.role.description": "Sélectionnez un rôle",
    "command.autoroles.add.reply.error.everyone": "Vous ne pouvez pas définir @everyone comme rôle automatique.",
    "command.autoroles.add.reply.error.managed": "Ce rôle est géré par une autre application et ne peut pas être attribué manuellement.",
    "command.autoroles.add.reply.error.position": "Mes permissions sont insuffisantes pour attribuer le rôle automatique. Assurez-vous que l'un de mes rôles est supérieur à [role].",
    "command.autoroles.add.reply.error.alreadyUsed": "[role] est déjà un rôle automatique.",
    "command.autoroles.add.reply.success": "[role] est désormais un rôle automatique.",
    "command.autoroles.remove.description": "Supprime un rôle automatique",
    "command.autoroles.remove.role.description": "Sélectionnez un rôle",
    "command.autoroles.remove.reply.error.notUsed": "[role] n'est actuellement pas un rôle automatique.",
    "command.autoroles.remove.reply.success": "[role] n'est plus un rôle automatique.",
    "command.autoroles.list.description": "Affiche les rôles automatiques actuels",
    "command.autoroles.list.raw.description": "Génére vos rôles automatiques sous forme de fichier texte brut",
    "command.autoroles.list.reply.empty": "Ce serveur n'a aucun rôle automatique.",
    "command.autoroles.list.reply.warn.tooLong": "La liste dépasse la limite de caractères. Veuillez utiliser l'option de commande `raw`.",
    "command.stickyroles.description": "Réattribue les rôles aux utilisateurs au cas où ils quitteraient votre serveur et le rejoindraient à nouveau",
    "command.stickyroles.add.description": "Ajoute un nouveau rôle collant",
    "command.stickyroles.add.role.description": "Sélectionnez un role",
    "command.stickyroles.add.reply.error.everyone": "Vous ne pouvez pas définir @everyone comme rôle collant.",
    "command.stickyroles.add.reply.error.managed": "Ce rôle est géré par une autre application et ne peut pas être attribué manuellement.",
    "command.stickyroles.add.reply.error.position": "Mes permissions sont insuffisantes pour attribuer le rôle collant. Assurez-vous que l'un de mes rôles est supérieur à [role].",
    "command.stickyroles.add.reply.error.alreadyUsed": "[role] est déjà un rôle collant.",
    "command.stickyroles.add.reply.success": "[role] est désormais un rôle collant.",
    "command.stickyroles.remove.description": "Supprime un rôle collant",
    "command.stickyroles.remove.role.description": "Sélectionnez un rôle",
    "command.stickyroles.remove.reply.error.notUsed": "[role] n'est actuellement pas un rôle collant.",
    "command.stickyroles.remove.reply.success": "[role] n'est plus un rôle collant.",
    "command.stickyroles.list.description": "Affiche les rôles collants actuels",
    "command.stickyroles.list.raw.description": "Génère vos rôles collants sous forme de fichier texte brut",
    "command.stickyroles.list.reply.empty": "Ce serveur n'a aucun rôle collant.",
    "command.stickyroles.list.reply.warn.tooLong": "La liste dépasse la limite de caractères. Veuillez utiliser l'option de commande `raw`.",
    "command.connectroles.description": "Connecte des rôles enfants à un rôle parent qui sera attribué automatiquement",
    "command.connectroles.add.description": "Ajouter une nouvelle connexion de rôle",
    "command.connectroles.add.childRole.description": "Sélectionnez le rôle enfant",
    "command.connectroles.add.parentRole.description": "Sélectionnez le rôle parent",
    "command.connectroles.add.reply.error.sameRoles": "Les rôles sélectionnés sont les mêmes.",
    "command.connectroles.add.reply.error.everyone": "Vous ne pouvez connecter @everyone.",
    "command.connectroles.add.reply.error.managed": "[role] est géré par une autre application et ne peut pas être attribué manuellement.",
    "command.connectroles.add.reply.error.position": "Mes permissions sont insuffisantes pour attribuer le rôle parent. Assurez-vous que l'un de mes rôles est supérieur à [role].",
    "command.connectroles.add.reply.error.childAlreadyConnected": "[role] est déjà connecté à un rôle parent.",
    "command.connectroles.add.reply.error.childAlreadyParent": "[role] est déjà connecté à un rôle parent.",
    "command.connectroles.add.reply.error.childAlreadyParentOfParent": "[parent] est déjà le rôle parent de [child]",
    "command.connectroles.add.reply.error.parentAlreadyChild": "[role] est déjà connecté à un rôle parent.",
    "command.connectroles.add.reply.success": "[child] est désormais un rôle enfant de [parent]",
    "command.connectroles.remove.description": "Supprime une connexion de rôle",
    "command.connectroles.remove.role.description": "Sélectionnez un rôle parent ou un rôle enfant",
    "command.connectroles.remove.reply.error.notConnected": "[role] n'est actuellement pas connecté.",
    "command.connectroles.remove.reply.success.childRemoved": "[role] a été déconnecté de son rôle parent.",
    "command.connectroles.remove.reply.success.parentRemoved": "Tous les rôles enfants de [role] ont été déconnectés.",
    "command.connectroles.list.description": "Afficher les connexions de rôle actuelles",
    "command.connectroles.list.raw.description": "Génére vos connexions de rôle sous forme de fichier texte `raw`",
    "command.connectroles.list.reply.empty": "Ce serveur n'a aucune connexion de rôle.",
    "command.connectroles.list.reply.warn.tooLong": "La liste dépasse la limite de caractères. Veuillez utiliser l'option de commande `raw`.",
    "command.connectroles.sync.description": "Synchronise les connexions de rôle - nécessaire uniquement si vous (dé)connectez des rôles déjà attribués",
    "command.connectroles.sync.reply.changes": "Changements",
    "command.connectroles.sync.reply.progress": "Progrès",
    "command.connectroles.sync.reply.start": "Synchronisation des connexions de rôle ...",
    "command.connectroles.sync.reply.finish": "Connexions de rôle synchronisées",
    "command.help.description": "À propos de moi",
    "command.help.reply.title": "Roles — Aide",
    "command.help.reply.description": "Nous publions des tutoriels de fonctionnalités sur notre **[chaîne YouTube](https://www.youtube.com/@rolesbot)**.",
    "command.help.reply.footer": "Développé par @pauel et @leonbrn",
    "command.help.reply.field1.name": "Rôles de Connexion — /connectroles",
    "command.help.reply.field1.value": "Connectez plusieurs rôles enfants à un rôle parent pour améliorer l'apparence et l'organisation de votre serveur..",
    "command.help.reply.field2.name": "Rôles Automatiques — /autoroles",
    "command.help.reply.field2.value": "Attribuez automatiquement des rôles aux nouveaux membres, en respectant les règles de filtrage.",
    "command.help.reply.field3.name": "Rôles Collants — /stickyroles",
    "command.help.reply.field3.value": "Réattribuez les rôles aux utilisateurs au cas où ils quitteraient votre serveur et le rejoindraient à nouveau.",
    "command.onCooldown": "Vous pouvez réutiliser cette commande [rtime].",
    "command.error": "**Une erreur s'est produite.** Veuillez réessayer plus tard ou contactez-nous sur notre serveur d'assistance.",
    "permission.required.all.text": "Toutes les permissions requises sont accordées.",
    "permission.required.missing.title": "Permissions manquantes",
    "permission.required.missing.text": "Le bot nécessite les permissions suivantes pour fonctionner correctement: [permissions]. Vous pouvez les attribuer manuellement au rôle de bot dans les paramètres de votre serveur ou ré-autoriser le bot ci-dessous.",
    "permission.required.reauthorize": "Ré-autoriser"
}

=== Schlafendes24/translations/it.json
{
    "$schema": "./_.schema.json",
    "addToServer": "Aggiungi al server",
    "appDirectory": "App Directory",
    "supportServer": "Server di supporto",
    "website": "Sito web",
    "error": "Errore",
    "command.autoroles.description": "Assegna automaticamente ruoli ai nuovi utenti",
    "command.autoroles.add.description": "Aggiungi un nuovo Auto Role",
    "command.autoroles.add.role.description": "Seleziona un ruolo",
    "command.autoroles.add.reply.error.everyone": "Non puoi impostare @everyone come Auto Role.",
    "command.autoroles.add.reply.error.managed": "Questo ruolo è gestito da un'altra applicazione, non può essere assegnato manualmente.",
    "command.autoroles.add.reply.error.position": "I miei permessi non sono sufficienti per assegnare questo ruolo. Assicurati che almeno uno dei miei ruoli sia sopra [role].",
    "command.autoroles.add.reply.error.alreadyUsed": "[role] è già un Auto Role.",
    "command.autoroles.add.reply.success": "[role] è ora un Auto Role.",
    "command.autoroles.remove.description": "Rimuovi un Auto Role",
    "command.autoroles.remove.role.description": "Seleziona un ruolo",
    "command.autoroles.remove.reply.error.notUsed": "[role] non è un Auto Role.",
    "command.autoroles.remove.reply.success": "[role] non è più un Auto Role.",
    "command.autoroles.list.description": "Mostra gli Auto Role configurati",
    "command.autoroles.list.raw.description": "Esporta i tuoi Auto Role in un file di testo",
    "command.autoroles.list.reply.empty": "Questo server non ha Auto Role.",
    "command.autoroles.list.reply.warn.tooLong": "La lista supera il limite di caratteri massimo. Seleziona l'opzione `raw` eseguendo nuovamente il comando.",
    "command.stickyroles.description": "Riassegna dei ruoli agli utenti che escono e rientrano nel server",
    "command.stickyroles.add.description": "Aggiungi un nuovo Sticky Role",
    "command.stickyroles.add.role.description": "Seleziona un ruolo",
    "command.stickyroles.add.reply.error.everyone": "Non puoi impostare @everyone come Sticky Role.",
    "command.stickyroles.add.reply.error.managed": "Questo ruolo è gestito da un'altra applicazione, non può essere assegnato manualmente.",
    "command.stickyroles.add.reply.error.position": "I miei permessi non sono sufficienti per assegnare questo ruolo. Assicurati che almeno uno dei miei ruoli sia sopra [role].",
    "command.stickyroles.add.reply.error.alreadyUsed": "[role] è già uno Sticky Role.",
    "command.stickyroles.add.reply.success": "[role] è ora uno Sticky Role.",
    "command.stickyroles.remove.description": "Rimuovi uno Sticky Role",
    "command.stickyroles.remove.role.description": "Seleziona un ruolo",
    "command.stickyroles.remove.reply.error.notUsed": "[role] non è uno Sticky Role.",
    "command.stickyroles.remove.reply.success": "[role] non è più uno Sticky Role.",
    "command.stickyroles.list.description": "Mostra gli Sticky Role configurati",
    "command.stickyroles.list.raw.description": "Esporta i tuoi Sticky Role in un file di testo",
    "command.stickyroles.list.reply.empty": "Questo server non ha Sticky Role.",
    "command.stickyroles.list.reply.warn.tooLong": "La lista supera il limite di caratteri massimo. Seleziona l'opzione `raw` eseguendo nuovamente il comando.",
    "command.connectroles.description": "Collega ruoli figli a dei ruoli padre che verranno assegnati automaticamente",
    "command.connectroles.add.description": "Aggiungi una nuova Role Connection",
    "command.connectroles.add.childRole.description": "Seleziona il ruolo figlio",
    "command.connectroles.add.parentRole.description": "Seleziona il ruolo padre",
    "command.connectroles.add.reply.error.sameRoles": "Hai selezionato due ruoli uguali.",
    "command.connectroles.add.reply.error.everyone": "Non puoi collegare il ruolo @everyone.",
    "command.connectroles.add.reply.error.managed": "[role] è gestito da un'altra applicazione, non può essere assegnato manualmente.",
    "command.connectroles.add.reply.error.position": "I miei permessi non sono sufficienti per assegnare il ruolo padre. Assicurati che almeno uno dei miei ruoli sia sopra [role].",
    "command.connectroles.add.reply.error.childAlreadyConnected": "[role] è già collegato ad un ruolo padre.",
    "command.connectroles.add.reply.error.childAlreadyParent": "[role] è già configurato come un ruolo padre.",
    "command.connectroles.add.reply.error.childAlreadyParentOfParent": "[parent] è già il ruolo padre di [child].",
    "command.connectroles.add.reply.error.parentAlreadyChild": "[role] è già configurato come un ruolo figlio.",
    "command.connectroles.add.reply.success": "[child] è ora un ruolo figlio di [parent].",
    "command.connectroles.remove.description": "Rimuovi una Role Connection",
    "command.connectroles.remove.role.description": "Seleziona un ruolo figlio o un ruolo padre",
    "command.connectroles.remove.reply.error.notConnected": "[role] non è collegato a nessun altro ruolo.",
    "command.connectroles.remove.reply.success.childRemoved": "[role] è stato scollegato dal suo ruolo padre.",
    "command.connectroles.remove.reply.success.parentRemoved": "Tutti i ruoli figli di [role] sono stati scollegati.",
    "command.connectroles.list.description": "Mostra le Role Connection configurate",
    "command.connectroles.list.raw.description": "Esporta le tue Role Connection in un file di testo",
    "command.connectroles.list.reply.empty": "Questo server non ha Role Connection.",
    "command.connectroles.list.reply.warn.tooLong": "La lista supera il limite di caratteri massimo. Seleziona l'opzione `raw` eseguendo nuovamente il comando.",
    "command.connectroles.sync.description": "Sincronizza le Role Connection - necessario solo se hai (s)collegato ruoli già assegnati",
    "command.connectroles.sync.reply.changes": "Cambiamenti",
    "command.connectroles.sync.reply.progress": "Progresso",
    "command.connectroles.sync.reply.start": "Sincronizzando le Role Connection ...",
    "command.connectroles.sync.reply.finish": "Role Connection sincronizzate",
    "command.help.description": "Informazioni utili",
    "command.help.reply.title": "Roles — Help",
    "command.help.reply.description": "Pubblichiamo dei tutorial sul nostro **[canale YouTube](https://www.youtube.com/@rolesbot)**.",
    "command.help.reply.footer": "Sviluppato da @pauel e @leonbrn",
    "command.help.reply.field1.name": "Role Connection — /connectroles",
    "command.help.reply.field1.value": "Collega diversi ruoli figli ad un ruolo padre, in modo tale da assegnare il ruolo padre automaticamente quando un utente ottiene uno dei ruoli figli.",
    "command.help.reply.field2.name": "Auto Role — /autoroles",
    "command.help.reply.field2.value": "Assegna automaticamente dei ruoli ai nuovi membri, dopo aver accettato le regole del server.",
    "command.help.reply.field3.name": "Sticky Role — /stickyroles",
    "command.help.reply.field3.value": "Configura dei ruoli che verranno riassegnati quando un utente esce e rientra nel server.",
    "command.onCooldown": "Potrai usare nuovamente questo comando [rtime].",
    "command.error": "**Qualcosa è andato storto.** Riprova più tardi o contattaci nel nostro server di supporto.",
    "permission.required.all.text": "Tutti i permessi necessari sono stati forniti.",
    "permission.required.missing.title": "Permessi mancanti",
    "permission.required.missing.text": "Il bot necessita dei seguenti permessi per funzionare correttamente: [permissions]. Puoi assegnarli bot manualmente al ruolo del bot nelle impostazioni del server, oppure autorizzare nuovamente il bot qua sotto.",
    "permission.required.reauthorize": "Autorizza"
}
