=== Schlafendes24/translations/_.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Translation",
    "description": "Roles language translation schema",
    "type": "object",
    "properties": {
        "addToServer": {
            "type": "string",
            "msgType": "default"
        },
        "appDirectory": {
            "type": "string",
            "msgType": "default"
        },
        "supportServer": {
            "type": "string",
            "msgType": "default"
        },
        "website": {
            "type": "string",
            "msgType": "default"
        },
        "error": {
            "type": "string",
            "msgType": "error"
        },
        "command.help.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.title": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field1.name": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field1.value": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field2.name": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field2.value": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field3.name": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.field3.value": {
            "type": "string",
            "msgType": "default"
        },
        "command.help.reply.footer": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.add.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.add.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.add.reply.error.everyone": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.error.managed": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.error.position": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.error.alreadyUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.add.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.autoroles.remove.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.remove.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.remove.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.autoroles.remove.reply.error.notUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.autoroles.list.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.list.raw.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.autoroles.list.reply.empty": {
            "type": "string",
            "msgType": "empty"
        },
        "command.autoroles.list.reply.warn.tooLong": {
            "type": "string",
            "msgType": "warn"
        },
        "command.stickyroles.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.add.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.add.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.add.reply.error.everyone": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.error.managed": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.error.position": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.error.alreadyUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.add.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.stickyroles.remove.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.remove.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.remove.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.stickyroles.remove.reply.error.notUsed": {
            "type": "string",
            "msgType": "error"
        },
        "command.stickyroles.list.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.list.raw.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.stickyroles.list.reply.empty": {
            "type": "string",
            "msgType": "empty"
        },
        "command.stickyroles.list.reply.warn.tooLong": {
            "type": "string",
            "msgType": "warn"
        },
        "command.connectroles.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.childRole.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.parentRole.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.add.reply.error.sameRoles": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.everyone": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.managed": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.position": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.childAlreadyConnected": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.add.reply.error.parentAlreadyChild": {
            "type": "string",
            "msgType": "error",
            "deprecated": false
        },
        "command.connectroles.add.reply.error.childAlreadyParent": {
            "type": "string",
            "msgType": "error",
            "deprecated": false
        },
        "command.connectroles.add.reply.error.childAlreadyParentOfParent": {
            "type": "string",
            "msgType": "error",
            "deprecated": true
        },
        "command.connectroles.add.reply.success": {
            "type": "string",
            "msgType": "success"
        },
        "command.connectroles.remove.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.remove.role.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.remove.reply.success.childRemoved": {
            "type": "string",
            "msgType": "success"
        },
        "command.connectroles.remove.reply.success.parentRemoved": {
            "type": "string",
            "msgType": "success"
        },
        "command.connectroles.remove.reply.error.notConnected": {
            "type": "string",
            "msgType": "error"
        },
        "command.connectroles.list.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.list.raw.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.list.reply.empty": {
            "type": "string",
            "msgType": "empty"
        },
        "command.connectroles.list.reply.warn.tooLong": {
            "type": "string",
            "msgType": "warn"
        },
        "command.connectroles.sync.description": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.start": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.finish": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.progress": {
            "type": "string",
            "msgType": "default"
        },
        "command.connectroles.sync.reply.changes": {
            "type": "string",
            "msgType": "default"
        },
        "command.onCooldown": {
            "type": "string",
            "msgType": "default"
        },
        "command.error": {
            "type": "string",
            "msgType": "error"
        },
        "permission.required.all.text": {
            "type": "string",
            "msgType": "default"
        },
        "permission.required.missing.title": {
            "type": "string",
            "msgType": "warn"
        },
        "permission.required.missing.text": {
            "type": "string",
            "msgType": "default"
        },
        "permission.required.reauthorize": {
            "type": "string",
            "msgType": "default"
        }
    }
}

=== Schlafendes24/translations/en_us.json
{
    "$schema": "../i18n.schema.json",
    "addToServer": "Add to Server",
    "appDirectory": "App Directory",
    "supportServer": "Support Server",
    "website": "Website",
    "error": "Error",
    "command.autoroles.description": "Automatically assign roles to new members",
    "command.autoroles.add.description": "Add a new Auto Role",
    "command.autoroles.add.role.description": "Select a role",
    "command.autoroles.add.reply.error.everyone": "You can not set @everyone as an Auto Role.",
    "command.autoroles.add.reply.error.managed": "This role is managed by another application and can not be assigned manually.",
    "command.autoroles.add.reply.error.position": "My permissions are not sufficient to assign the Auto Role. Make sure any of my roles is above [role].",
    "command.autoroles.add.reply.error.alreadyUsed": "[role] is already an Auto Role.",
    "command.autoroles.add.reply.success": "[role] is now an Auto Role.",
    "command.autoroles.remove.description": "Remove an Auto Role",
    "command.autoroles.remove.role.description": "Select a role",
    "command.autoroles.remove.reply.error.notUsed": "[role] is currently not an Auto Role.",
    "command.autoroles.remove.reply.success": "[role] is no longer an Auto Role.",
    "command.autoroles.list.description": "Display the current Auto Roles",
    "command.autoroles.list.raw.description": "Output your Auto Roles as a raw text file",
    "command.autoroles.list.reply.empty": "This server does not have any Auto Roles.",
    "command.autoroles.list.reply.warn.tooLong": "The list exceeds the character limit. Please use the `raw` command option.",
    "command.stickyroles.description": "Reassign roles to users in case they leave your server and join again",
    "command.stickyroles.add.description": "Add a new Sticky Role",
    "command.stickyroles.add.role.description": "Select a role",
    "command.stickyroles.add.reply.error.everyone": "You can not set @everyone as a Sticky Role.",
    "command.stickyroles.add.reply.error.managed": "This role is managed by another application and can not be assigned manually.",
    "command.stickyroles.add.reply.error.position": "My permissions are not sufficient to assign the Sticky Role. Make sure any of my roles is above [role].",
    "command.stickyroles.add.reply.error.alreadyUsed": "[role] is already a Sticky Role.",
    "command.stickyroles.add.reply.success": "[role] is now a Sticky Role.",
    "command.stickyroles.remove.description": "Remove a Sticky Role",
    "command.stickyroles.remove.role.description": "Select a role",
    "command.stickyroles.remove.reply.error.notUsed": "[role] is currently not a Sticky Role.",
    "command.stickyroles.remove.reply.success": "[role] is no longer a Sticky Role.",
    "command.stickyroles.list.description": "Display the current Sticky Roles",
    "command.stickyroles.list.raw.description": "Output your Sticky Roles as a raw text file",
    "command.stickyroles.list.reply.empty": "This server does not have any Sticky Roles.",
    "command.stickyroles.list.reply.warn.tooLong": "The list exceeds the character limit. Please use the `raw` command option.",
    "command.connectroles.description": "Connect child roles to a parent role that will be assigned automatically",
    "command.connectroles.add.description": "Add a new Role Connection",
    "command.connectroles.add.childRole.description": "Select the child role",
    "command.connectroles.add.parentRole.description": "Select the parent role",
    "command.connectroles.add.reply.error.sameRoles": "The selected roles are the same.",
    "command.connectroles.add.reply.error.everyone": "You can not connect @everyone.",
    "command.connectroles.add.reply.error.managed": "[role] is managed by another application and can not be assigned manually.",
    "command.connectroles.add.reply.error.position": "My permissions are not sufficient to assign the parent role. Make sure any of my roles is above [role].",
    "command.connectroles.add.reply.error.childAlreadyConnected": "[role] is already connected to a parent role.",
    "command.connectroles.add.reply.error.childAlreadyParent": "[role] is already connected to a parent role.",
    "command.connectroles.add.reply.error.childAlreadyParentOfParent": "[parent] is already the parent role if [child]",
    "command.connectroles.add.reply.error.parentAlreadyChild": "[role] is already connected to a parent role.",
    "command.connectroles.add.reply.success": "[child] is now a child role of [parent]",
    "command.connectroles.remove.description": "Remove a Role Connection",
    "command.connectroles.remove.role.description": "Select a parent role or a child role",
    "command.connectroles.remove.reply.error.notConnected": "[role] is currently not connected.",
    "command.connectroles.remove.reply.success.childRemoved": "[role] has been disconnected from its parent role.",
    "command.connectroles.remove.reply.success.parentRemoved": "All child roles of [role] have been disconnected.",
    "command.connectroles.list.description": "Display the current Role Connections",
    "command.connectroles.list.raw.description": "Output your Role Connections as a raw text file",
    "command.connectroles.list.reply.empty": "This server does not have any Role Connections.",
    "command.connectroles.list.reply.warn.tooLong": "The list exceeds the character limit. Please use the `raw` command option.",
    "command.connectroles.sync.description": "Syncs the Role Connections - only necessary if you (dis)connected already assigned roles",
    "command.connectroles.sync.reply.changes": "Changes",
    "command.connectroles.sync.reply.progress": "Progress",
    "command.connectroles.sync.reply.start": "Syncing Role Connections ...",
    "command.connectroles.sync.reply.finish": "Synced Role Connections",
    "command.help.description": "About me",
    "command.help.reply.title": "Roles — Help",
    "command.help.reply.description": "We post feature tutorials on our **[YouTube channel](https://www.youtube.com/@rolesbot)**.",
    "command.help.reply.footer": "Developed by @pauel and @leonbrn",
    "command.help.reply.field1.name": "Connection Roles — /connectroles",
    "command.help.reply.field1.value": "Connect multiple child roles to a parent role to improve the look and organization of your server.",
    "command.help.reply.field2.name": "Auto Roles — /autoroles",
    "command.help.reply.field2.value": "Automatically assign roles to new members, respecting Rules Screening.",
    "command.help.reply.field3.name": "Sticky Roles — /stickyroles",
    "command.help.reply.field3.value": "Reassign roles to users in case they leave your server and join again.",
    "command.onCooldown": "You can use this command again [rtime].",
    "command.error": "**An error occured.** Please try again later or contact us on our support server.",
    "permission.required.all.text": "All required permissions are granted.",
    "permission.required.missing.title": "Missing permissions",
    "permission.required.missing.text": "The bot requires the following permissions in order to function properly: [permissions]. You can manually assign them to the bot role in your server settings or reauthorize the bot below.",
    "permission.required.reauthorize": "Reauthorize"
}

=== Schlafendes24/translations/ru.json
{
    "$schema": "./_.schema.json",
    "addToServer": "Добавить на сервер",
    "appDirectory": "Каталог Приложений",
    "supportServer": "Сервер Поддержки",
    "website": "Сайт",
    "error": "Ошибка",
    "command.autoroles.description": "Автоматически назначать роли новым участникам",
    "command.autoroles.add.description": "Добавить Auto Role",
    "command.autoroles.add.role.description": "Выберите роль",
    "command.autoroles.add.reply.error.everyone": "Вы не можете поставить @everyone Auto role.",
    "command.autoroles.add.reply.error.managed": "Эта роль приложения, вы не можете назначить её.",
    "command.autoroles.add.reply.error.position": "У меня недостаточно прав для назначения Auto Roles. Убедитесь, что какая-либо из моих ролей выше [role].",
    "command.autoroles.add.reply.error.alreadyUsed": "[role] уже Auto Role.",
    "command.autoroles.add.reply.success": "[role] теперь Auto Role.",
    "command.autoroles.remove.description": "Убрать Auto Role",
    "command.autoroles.remove.role.description": "Выберите роль",
    "command.autoroles.remove.reply.error.notUsed": "[role] не является Auto Role.",
    "command.autoroles.remove.reply.success": "[role] больше не Auto Role.",
    "command.autoroles.list.description": "Все текущие Auto Roles",
    "command.autoroles.list.raw.description": "Вывести все Auto Roles в текстовый файл",
    "command.autoroles.list.reply.empty": "У данного сервера нету Auto Roles.",
    "command.autoroles.list.reply.warn.tooLong": "Количество символов в списке превышает допустимое. Пожалуйста, используйте команду `raw`.",
    "command.stickyroles.description": "Назначить роли участников, если они вышли и вошли на сервер снова",
    "command.stickyroles.add.description": "Добавить новую Sticky Role",
    "command.stickyroles.add.role.description": "Выберите роль",
    "command.stickyroles.add.reply.error.everyone": "Вы не можете поставить @everyone Sticky Role.",
    "command.stickyroles.add.reply.error.managed": "Эта роль приложения, вы не можете назначить её.",
    "command.stickyroles.add.reply.error.position": "У меня недостаточно прав для назначения Sticky Role. Убедитесь, что какая-либо из моих ролей выше [role].",
    "command.stickyroles.add.reply.error.alreadyUsed": "[role] уже Sticky Role.",
    "command.stickyroles.add.reply.success": "[role] теперь Sticky Role.",
    "command.stickyroles.remove.description": "Убрать Sticky Role",
    "command.stickyroles.remove.role.description": "Выберете",
    "command.stickyroles.remove.reply.error.notUsed": "[role] не является Sticky Role.",
    "command.stickyroles.remove.reply.success": "[role] больше не Sticky Role.",
    "command.stickyroles.list.description": "Все текущие Sticky Roles",
    "command.stickyroles.list.raw.description": "Вывести все Sticky Roles в текстовый файл",
    "command.stickyroles.list.reply.empty": "Сервер не имеет Sticky Roles.",
    "command.stickyroles.list.reply.warn.tooLong": "Количество символов в списке превышает допустимое. Пожалуйста, используйте команду `raw`.",
    "command.connectroles.description": "Подключите дочерние роли к родительской, которая будет назначена автоматически.",
    "command.connectroles.add.description": "Добавить новую Role Connection",
    "command.connectroles.add.childRole.description": "Выберите дочерную роль",
    "command.connectroles.add.parentRole.description": "Выберите родительскую роль",
    "command.connectroles.add.reply.error.sameRoles": "Выбранные роли одинаковые.",
    "command.connectroles.add.reply.error.everyone": "Вы не можете выбрать @everyone.",
    "command.connectroles.add.reply.error.managed": "[role] является приложением и не может быть выбрана",
    "command.connectroles.add.reply.error.position": "У меня недостаточно прав для назначения родительской роли. Убедитесь, что какая-либо из моих ролей выше [role].",
    "command.connectroles.add.reply.error.childAlreadyConnected": "[role] уже подключена к родительской роли.",
    "command.connectroles.add.reply.error.childAlreadyParent": "[role] уже подключена к родительской роли.",
    "command.connectroles.add.reply.error.childAlreadyParentOfParent": "[parent] же подключена к родительской роли если [child]",
    "command.connectroles.add.reply.error.parentAlreadyChild": "[role] уже подключена к родительской роли.",
    "command.connectroles.add.reply.success": "[child] теперь дочерняя роль по отношению к [parent]",
    "command.connectroles.remove.description": "Убрать Role Connection",
    "command.connectroles.remove.role.description": "Выберите родительскую или дочерную роль",
    "command.connectroles.remove.reply.error.notConnected": "[role] в данный момент не подключена.",
    "command.connectroles.remove.reply.success.childRemoved": "[role] была  отключена от родительской роли",
    "command.connectroles.remove.reply.success.parentRemoved": "Все дочерние роли [role] были отключены.",
    "command.connectroles.list.description": "Все текущие Role Connections",
    "command.connectroles.list.raw.description": "Вывести все Role Connections в текстовый файл",
    "command.connectroles.list.reply.empty": "Этот сервер не имеет Role Connections.",
    "command.connectroles.list.reply.warn.tooLong": "Количество символов в списке превышает допустимое. Пожалуйста, используйте команду `raw`.",
    "command.connectroles.sync.description": "Синхронизация Role Connections - только если вы отключили/подключили уже распределённые роли",
    "command.connectroles.sync.reply.changes": "Изменения",
    "command.connectroles.sync.reply.progress": "Програсс",
    "command.connectroles.sync.reply.start": "Синхронизация Role Connections ...",
    "command.connectroles.sync.reply.finish": "Синхронизация Role Connections прошла успешно",
    "command.help.description": "Обо мне",
    "command.help.reply.title": "Roles — Помощь",
    "command.help.reply.description": "Мы публикуем туториалы на **[YouTube канале](https://www.youtube.com/@rolesbot)**.",
    "command.help.reply.footer": "Разработаны @pauel и @leonbrn",
    "command.help.reply.field1.name": "Connection Roles — /connectroles",
    "command.help.reply.field1.value": "Подключите несколько дочерних ролей к родительской, чтобы улучшить внешний вид и организацию вашего сервера.",
    "command.help.reply.field2.name": "Auto Roles — /autoroles",
    "command.help.reply.field2.value": "Назначайте Auto Roles новым участникам соблюдая правила",
    "command.help.reply.field3.name": "Sticky Roles — /stickyroles",
    "command.help.reply.field3.value": "Назначте роли участников, если они вышли и вошли на сервер снова",
    "command.onCooldown": "Вы можете использовать команду снова через [rtime].",
    "command.error": "**Произошла ошибка** Попробуйте снова позже или свяжитесь с нами через сервер поддержки",
    "permission.required.all.text": "Все необходимые права предоставлены.",
    "permission.required.missing.title": "Отсутствуют необходимое(ые) права",
    "permission.required.missing.text": "Для правильной работы, боту требуются следующие разрешения: [permissions]. Вы можете назначить их вручную или повторно авторизовать бота ниже.",
    "permission.required.reauthorize": "Повторная авторизация"
}

=== Schlafendes24/translations/_empty.json
{
    "$schema": "../i18n.schema.json",
    "addToServer": "",
    "appDirectory": "",
    "supportServer": "",
    "website": "",
    "error": "",
    "command.autoroles.description": "",
    "command.autoroles.add.description": "",
    "command.autoroles.add.role.description": "",
    "command.autoroles.add.reply.error.everyone": "",
    "command.autoroles.add.reply.error.managed": "",
    "command.autoroles.add.reply.error.position": "",
    "command.autoroles.add.reply.error.alreadyUsed": "",
    "command.autoroles.add.reply.success": "",
    "command.autoroles.remove.description": "",
    "command.autoroles.remove.role.description": "",
    "command.autoroles.remove.reply.error.notUsed": "",
    "command.autoroles.remove.reply.success": "",
    "command.autoroles.list.description": "",
    "command.autoroles.list.raw.description": "",
    "command.autoroles.list.reply.empty": "",
    "command.autoroles.list.reply.warn.tooLong": "",
    "command.stickyroles.description": "",
    "command.stickyroles.add.description": "",
    "command.stickyroles.add.role.description": "",
    "command.stickyroles.add.reply.error.everyone": "",
    "command.stickyroles.add.reply.error.managed": "",
    "command.stickyroles.add.reply.error.position": "",
    "command.stickyroles.add.reply.error.alreadyUsed": "",
    "command.stickyroles.add.reply.success": "",
    "command.stickyroles.remove.description": "",
    "command.stickyroles.remove.role.description": "",
    "command.stickyroles.remove.reply.error.notUsed": "",
    "command.stickyroles.remove.reply.success": "",
    "command.stickyroles.list.description": "",
    "command.stickyroles.list.raw.description": "",
    "command.stickyroles.list.reply.empty": "",
    "command.stickyroles.list.reply.warn.tooLong": "",
    "command.connectroles.description": "",
    "command.connectroles.add.description": "",
    "command.connectroles.add.childRole.description": "",
    "command.connectroles.add.parentRole.description": "",
    "command.connectroles.add.reply.error.sameRoles": "",
    "command.connectroles.add.reply.error.everyone": "",
    "command.connectroles.add.reply.error.managed": "",
    "command.connectroles.add.reply.error.position": "",
    "command.connectroles.add.reply.error.childAlreadyConnected": "",
    "command.connectroles.add.reply.error.childAlreadyParent": "",
    "command.connectroles.add.reply.error.childAlreadyParentOfParent": "",
    "command.connectroles.add.reply.error.parentAlreadyChild": "",
    "command.connectroles.add.reply.success": "",
    "command.connectroles.remove.description": "",
    "command.connectroles.remove.role.description": "",
    "command.connectroles.remove.reply.error.notConnected": "",
    "command.connectroles.remove.reply.success.childRemoved": "",
    "command.connectroles.remove.reply.success.parentRemoved": "",
    "command.connectroles.list.description": "",
    "command.connectroles.list.raw.description": "",
    "command.connectroles.list.reply.empty": "",
    "command.connectroles.list.reply.warn.tooLong": "",
    "command.connectroles.sync.description": "",
    "command.connectroles.sync.reply.changes": "",
    "command.connectroles.sync.reply.progress": "",
    "command.connectroles.sync.reply.start": "",
    "command.connectroles.sync.reply.finish": "",
    "command.help.description": "",
    "command.help.reply.title": "",
    "command.help.reply.description": "",
    "command.help.reply.footer": "",
    "command.help.reply.field1.name": "",
    "command.help.reply.field1.value": "",
    "command.help.reply.field2.name": "",
    "command.help.reply.field2.value": "",
    "command.help.reply.field3.name": "",
    "command.help.reply.field3.value": "",
    "command.onCooldown": "",
    "command.error": "",
    "permission.required.all.text": "",
    "permission.required.missing.title": "",
    "permission.required.missing.text": "",
    "permission.required.reauthorize": ""
}
